# Generated by Django 2.2.3 on 2020-07-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_m_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_lebel', models.IntegerField()),
                ('parent_category_id', models.IntegerField()),
                ('category_text', models.CharField(max_length=20)),
                ('del_flg', models.IntegerField(default=0)),
                ('create_day', models.DateTimeField(verbose_name='date published')),
                ('updata_day', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='job_t_diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(error_messages={'required': '必須です!'}, max_length=20)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(error_messages={'required': '必須です!'}, max_length=80)),
                ('diary', models.CharField(error_messages={'required': '必須です!'}, max_length=1000)),
                ('delete_frg', models.IntegerField(default=0)),
                ('create_day', models.DateTimeField(verbose_name='date published')),
                ('like_number', models.IntegerField(default=0)),
                ('comment_number', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.job_m_category')),
            ],
        ),
        migrations.CreateModel(
            name='job_t_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.URLField()),
                ('create_day', models.DateTimeField(verbose_name='date published')),
                ('updata_day', models.DateTimeField(verbose_name='date published')),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.job_t_diary')),
                ('pic_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.job_t_user')),
            ],
        ),
        migrations.CreateModel(
            name='job_t_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(error_messages={'required': '必須です!'}, max_length=20)),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(error_messages={'required': '必須です!'}, max_length=1000)),
                ('delete_frg', models.IntegerField(default=0)),
                ('create_day', models.DateTimeField(verbose_name='date published')),
                ('comment_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.job_t_diary')),
            ],
        ),
    ]
