# Generated by Django 2.2.3 on 2020-07-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_t_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.IntegerField(default=1)),
                ('del_flg', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=20)),
                ('user_create_day', models.DateTimeField(verbose_name='date published')),
                ('user_updata_day', models.DateTimeField(verbose_name='date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job_t_a_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.URLField()),
                ('create_day', models.DateTimeField(verbose_name='date published')),
                ('updata_day', models.DateTimeField(verbose_name='date published')),
                ('pic_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.job_t_user')),
            ],
        ),
    ]
